### ISSUE TITLE
Exception trying to build

### ISSUE THREAD

**Issue by guilhermeolisi** [ahopper/Avalonia.IconPacks#5]
Hi,

I cloned your project and tried to build it in VS 2022 but got an exception. Can you help me to resolve this? I don't understand this problem.
Thanks

System.TypeInitializationException
HResult=0x80131534
Message=The type initializer for 'NamespaceInfo:/App.xaml' threw an exception.
Source=Avalonia.IconPacks
StackTrace:
at Avalonia.IconPacks.App.!XamlIlPopulate(IServiceProvider , App ) in C:\Users\guilh\Documents\Acadêmico\VisualStudio\AvaloniaIconPacks\src\Avalonia.IconPacks\App.xaml:line 1
at Avalonia.IconPacks.App.!XamlIlPopulateTrampoline(App )
at Avalonia.IconPacks.App.Initialize() in C:\Users\guilh\Documents\Acadêmico\VisualStudio\AvaloniaIconPacks\src\Avalonia.IconPacks\App.xaml.cs:line 12
at Avalonia.Controls.AppBuilderBase`1.Setup()
at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
at Avalonia.IconPacks.Program.Main(String[] args) in C:\Users\guilh\Documents\Acadêmico\VisualStudio\AvaloniaIconPacks\src\Avalonia.IconPacks\Program.cs:line 19

This exception was originally thrown at this call stack:
[External Code]

Inner Exception 1:
BadImageFormatException: No string associated with token. The format of the file 'C:\Users\guilh\Documents\Acadêmico\VisualStudio\AvaloniaIconPacks\src\Avalonia.IconPacks\bin\x64\Debug\net6.0\Avalonia.IconPacks.dll' is invalid.

**Comment by devel0** [comment]
I got the same error (linux) and I was able to solve by issueing the cmd used in the [workflow](https://github.com/ahopper/Avalonia.IconPacks/blob/c5a4aceeae8801f8ee4ab70e7955582aaecdd074/.github/workflows/dotnetcore.yml#L17)

```sh
dotnet publish ./src/Avalonia.IconPacks/Avalonia.IconPacks.csproj -r linux-x64 --self-contained -c Release -f net6.0 /p:PublishTrimmed=true /p:PublishLinux=True
```

then

```
cd src/Avalonia.IconPacks/bin/Release/net6.0/linux-x64/publish/
./Avalonia.IconPacks
```

**Comment by guilhermeolisi** [comment]
> I got the same error (linux) and I was able to solve by issueing the cmd used in the [workflow](https://github.com/ahopper/Avalonia.IconPacks/blob/c5a4aceeae8801f8ee4ab70e7955582aaecdd074/.github/workflows/dotnetcore.yml#L17)
> 
> ```shell
> dotnet publish ./src/Avalonia.IconPacks/Avalonia.IconPacks.csproj -r linux-x64 --self-contained -c Release -f net6.0 /p:PublishTrimmed=true /p:PublishLinux=True
> ```
> 
> then
> 
> ```
> cd src/Avalonia.IconPacks/bin/Release/net6.0/linux-x64/publish/
> ./Avalonia.IconPacks
> ```

Thanks, I will try this in my Windows system.

**Comment by devel0** [comment]
the corresponding in window from [workflow](https://github.com/ahopper/Avalonia.IconPacks/blob/c5a4aceeae8801f8ee4ab70e7955582aaecdd074/.github/workflows/dotnetcore.yml#L34) should be

```sh
dotnet publish ./src/Avalonia.IconPacks/Avalonia.IconPacks.csproj -r win-x64 --self-contained -c Release -f net6.0 /p:PublishTrimmed=true  /p:PublishWin=True
```

then

```sh
cd src/Avalonia.IconPacks/bin/Release/net6.0/win-x64/publish/
./Avalonia.IconPacks
```

**Comment by ahopper** [comment]
sorry I missed this issue, notifications were being sent to spam.  
The publishWin publishOsx and publishLinux switches shrink the app a little as it avoids including some xplat code.  I believe this wont be needed in Avalonia 11.0
